// Importing
import {StyleSheet} from 'react-native';
import {scale} from 'react-native-size-matters';
import COLORS from '../../config/COLORS';
import FONTS from '../../config/FONTS';
import shadow from '../../components/SHADOW';

// Exporting
export default HOME_STYLES = StyleSheet.create({
  contentContainer: {
    flex: 1,
  },
  header: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: scale(10),
    position: 'absolute',
    left: 0,
    top: 0,
    bottom:0,
    right: 0,
    zIndex: 10,
    height: scale(60),
    justifyContent: 'space-evenly',
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
  },
  circleLogoView: {
    width: scale(40),
    height: scale(40),
    backgroundColor: COLORS.white,
    padding: scale(5),
    borderRadius: scale(20),
    marginLeft: scale(10),
  },
  circleLogoViewCopy: {
    width: scale(40),
    height: scale(40),
    backgroundColor: COLORS.primary,
    textAlign:'center',
    alignItems: 'center',
    justifyContent:'center',
    borderRadius: scale(20),
    marginLeft: scale(10),
    
  },
  circleUserView: {
    width: scale(40),
    height: scale(40),
    backgroundColor: COLORS.primaryDark,
    padding: scale(5),
    borderRadius: scale(20),
    marginLeft: scale(10),
  },
  headerRight: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  micIconContainer: {
    marginRight: scale(10),
    marginTop: scale(5),
  },
  menuOptions: {
    backgroundColor: COLORS.darkGrey,
    padding: scale(10),
    borderRadius: scale(5),
    color:COLORS.white,
    width: scale(220),
    marginTop:20,
    zIndex:100000,
    ...shadow(10, COLORS.shadowDark),
  },
  menuOptionWrapper: {
    padding: scale(10),
  },
  menuOptionText: {
    fontFamily: FONTS.families.OpenSansRegular,
    fontSize: scale(FONTS.sizes.small),
    letterSpacing: scale(0.5),
    color: COLORS.white,
    fontWeight:'700',
  },
  searchBarContainer: {
    position: 'relative',
    backgroundColor: COLORS.white,
    height: scale(0.1),
    borderRadius: scale(5),
    overflow: 'hidden',
  },
  searchBarInput: {
    flex: 1,
    paddingHorizontal: scale(10),
    fontSize: scale(FONTS.sizes.xSmall),
    fontFamily: FONTS.families.OpenSansSemiBold,
    color: COLORS.fontDark,
    letterSpacing: scale(0.5),
  },
  searchBarIcon: {
    position: 'absolute',
    right: scale(10),
    top: scale(5),
  },
  innerContainer: {
    marginHorizontal: scale(10),
  },
  innerContainerCopy: {
    position:'absolute',
    width:'100%',
    top:'10%',
    margin:'2%'
    
  },
  mainSlider: {
    height: scale(200),
    marginTop: scale(35),
  },
  mainSliderEng: {
    marginTop: scale(50),
  },
  swiper: {},
  slide: {
    flex: 1,
  },
  swiperPagination: {
    bottom: scale(24),
  },
  dotDefault: {
    backgroundColor: COLORS.grey,
    width: scale(11),
    height: scale(11),
    borderRadius: scale(5.5),
    marginLeft: scale(3),
    marginRight: scale(3),
    marginTop: scale(3),
    marginBottom: scale(3),
    borderWidth: scale(1),
    borderColor: COLORS.darkGrey,
  },
  dotActive: {
    backgroundColor: COLORS.primary,
    width: scale(11),
    height: scale(11),
    borderRadius: scale(5.5),
    marginLeft: scale(3),
    marginRight: scale(3),
    marginTop: scale(3),
    marginBottom: scale(3),
  },
  featuresContainer: {
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: scale(10),
    borderRadius: scale(5),
    marginTop: scale(5),
    marginBottom: scale(17.5),
    borderWidth: scale(1),
    borderColor: COLORS.borderGrey,
  },
  featuresContainerCopy: {
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: scale(10),
    borderRadius: scale(5),
    marginTop: scale(25),
    marginBottom: scale(17.5),
    borderWidth: scale(1),
    borderColor: COLORS.borderGrey,
  },
  featureIconContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  featureIconImage: {
    width: scale(35),
    height: scale(35),
    tintColor: COLORS.primary,
  },
  featureIconLabel: {
    fontSize: scale(FONTS.sizes.xSmall),
    fontFamily: FONTS.families.OpenSansSemiBold,
    letterSpacing: scale(0.5),
    color: COLORS.fontDark,
    textTransform: 'capitalize',
    marginTop: scale(5),
  },
  sectionHeadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: scale(17.5),
  },
  sectionHeadingContainerMarginTop: {
    marginTop: scale(17.5),
  },
  sectionHeading: {
    fontSize: scale(FONTS.sizes.medium),
    fontFamily: FONTS.families.MontserratMedium,
    letterSpacing: scale(0.5),
    color: COLORS.fontDark,
    textTransform: 'capitalize',
  },
  sectionHeadingBold: {
    fontFamily: FONTS.families.MontserratSemiBold,
  },
  productCardContainer: {
    width: scale(180),
  },
  spinWinBannerContainer: {
    height: scale(173),
    marginTop: scale(25),
    borderRadius: scale(10),
    overflow: 'hidden',
    position: 'relative',
  },
  spinWinInfoContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    padding: scale(10),
  },
  spinWinTitle: {
    fontSize: scale(FONTS.sizes.medium),
    fontFamily: FONTS.families.MontserratMedium,
    letterSpacing: scale(0.5),
    color: COLORS.white,
    textTransform: 'uppercase',
    marginBottom: scale(7.5),
  },
  spinWinParagraph: {
    fontSize: scale(FONTS.sizes.xSmall),
    fontFamily: FONTS.families.OpenSansRegular,
    letterSpacing: scale(0.5),
    color: COLORS.white,
  },
  confettiIconContainer: {
    position: 'absolute',
    width: scale(64),
    height: scale(64),
    bottom: scale(10),
    left: scale(10),
  },
  categoryImageContainer: {
    width: scale(130),
    height: scale(130),
    borderRadius: scale(10),
    overflow: 'hidden',
    position: 'relative',
  },
  categoryTitleContainer: {
    position: 'absolute',
    backgroundColor: COLORS.primary,
    bottom: scale(5),
    right: scale(5),
    paddingHorizontal: scale(12),
    paddingVertical: scale(3),
    borderTopLeftRadius: scale(15),
    borderBottomRightRadius: scale(15),
  },
  categoryTitleContainerCopy: {
    position: 'absolute',
    backgroundColor: COLORS.primary,
    bottom: scale(5),
    right: scale(5),
    paddingHorizontal: scale(12),
    paddingVertical: scale(1),
    borderTopLeftRadius: scale(15),
    borderBottomRightRadius: scale(15),
  },
  categoryTitle: {
    fontSize: scale(FONTS.sizes.xSmall),
    fontFamily: FONTS.families.OpenSansSemiBold,
    letterSpacing: scale(0.5),
    color: COLORS.white,
  },
  offerImageContainer: {
    width: scale(280),
    height: scale(140),
    borderRadius: scale(10),
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: 'red',
  },
  offerLabelContainer: {
    position: 'absolute',
    bottom: scale(5),
    left: scale(5),
    backgroundColor: COLORS.shadowDark,
    paddingHorizontal: scale(12),
    paddingVertical: scale(3),
    borderRadius: scale(5),
  },
  offerLabel: {
    fontSize: scale(FONTS.sizes.xSmall),
    fontFamily: FONTS.families.OpenSansSemiBold,
    letterSpacing: scale(0.5),
    color: COLORS.white,
    textTransform: 'capitalize',
  },
  brandImageContainer: {
    width: scale(70),
    height: scale(70),
    backgroundColor: COLORS.white,
    borderRadius: scale(50),
    borderWidth: scale(1),
    borderColor: COLORS.borderGrey,
  },
  brandImage: {
    width: scale(35),
    height: scale(35),
    tintColor: COLORS.primary,
  },
  saleCountdownContainer: {
    backgroundColor: COLORS.primary,
    height: scale(230),
    borderRadius: scale(10),
  },
  saleTitle: {
    color: COLORS.white,
    fontFamily: FONTS.families.MontserratSemiBold,
    fontSize: scale(FONTS.sizes.xLarge),
    textTransform: 'uppercase',
    letterSpacing: scale(0.5),
  },
  saleSubtitleContainer: {
    alignItems: 'center',
    marginTop: scale(10),
    marginBottom: scale(20),
  },
  saleSubtitleOne: {
    color: COLORS.primaryDark,
    fontFamily: FONTS.families.OpenSansSemiBold,
    fontSize: scale(FONTS.sizes.medium),
    textTransform: 'capitalize',
    letterSpacing: scale(0.5),
  },
  saleSubtitleTwo: {
    color: COLORS.white,
    fontFamily: FONTS.families.OpenSansRegular,
    fontSize: scale(FONTS.sizes.large),
    textTransform: 'capitalize',
    letterSpacing: scale(0.5),
  },
  countdownDigit: {
    backgroundColor: COLORS.primaryDark,
    marginHorizontal: scale(10),
  },
  countdownDigitTxt: {
    color: COLORS.white,
    fontFamily: FONTS.families.OpenSansRegular,
    fontSize: scale(FONTS.sizes.xLarge),
    letterSpacing: scale(0.5),
  },
  countdownTimeLabel: {
    color: COLORS.white,
    fontFamily: FONTS.families.OpenSansSemiBold,
    fontSize: scale(FONTS.sizes.xSmall),
    textTransform: 'capitalize',
    letterSpacing: scale(0.5),
    marginTop: scale(2.5),
  },
  countdownSeparator: {
    color: COLORS.primaryDark,
    top: scale(-12),
  },
  feedbackContainer: {
    height: scale(230),
    borderWidth: scale(1),
    borderColor: COLORS.borderGrey,
    borderRadius: scale(10),
    overflow: 'hidden',
  },
  feedbackSlide: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: scale(10),
    padding: scale(30),
  },
  customerImageContainer: {
    width: scale(70),
    height: scale(70),
    borderRadius: scale(35),
    overflow: 'hidden',
    marginBottom: scale(10),
  },
  feedbackTextContainer: {
    position: 'relative',
    marginTop: scale(10),
  },
  quoteLeft: {
    left: scale(0),
    top: scale(-20),
    position: 'absolute',
  },
  quoteRight: {
    right: scale(0),
    bottom: scale(-20),
    position: 'absolute',
  },
  feedbackText: {
    color: COLORS.fontLight,
    fontFamily: FONTS.families.OpenSansRegular,
    fontSize: scale(FONTS.sizes.xSmall),
    letterSpacing: scale(0.5),
    textAlign: 'center',
  },
  customerName: {
    color: COLORS.primary,
    fontFamily: FONTS.families.MontserratMedium,
    fontSize: scale(FONTS.sizes.small),
    letterSpacing: scale(0.5),
    marginTop: scale(20),
    textAlign: 'center',
    textTransform: 'capitalize',
  },
  customerDesignation: {
    color: COLORS.fontDark,
    fontFamily: FONTS.families.OpenSansSemiBold,
    fontSize: scale(FONTS.sizes.xSmall),
    letterSpacing: scale(0.5),
    marginVertical: scale(2.5),
  },
  feedbackRatingContainer: {
    flexDirection: 'row',
  },
  iconLabelContainer: {
    margin: scale(7.5),
    
  },
  billPayIconsContainerCopy: {
    backgroundColor: COLORS.white,
    borderRadius: scale(10),
    borderWidth: scale(1),
    borderColor: COLORS.borderGrey,
    margin:scale(10),
    padding:scale(7.5)
    
  },
  billPayIconsContainer: {
    backgroundColor: COLORS.white,
    padding: scale(7.5),
    borderRadius: scale(10),
    borderWidth: scale(1),
    borderColor: COLORS.borderGrey,
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  iconContainer: {
    width: scale(70),
    height: scale(70),
    backgroundColor: COLORS.primaryLightest,
    borderRadius: scale(35),
  },
  iconContainerCopy: {
    width: scale(70),
    height: scale(70),
    backgroundColor: COLORS.secondary,
    borderRadius: scale(35),
  },
  icon: {
    width: scale(35),
    height: scale(35),
    tintColor: COLORS.primary,
  },
  iconList: {
    width: scale(25),
    height: scale(25),
    tintColor: COLORS.primary,
  },
  iconCopy: {
    width: scale(35),
    height: scale(35),
    tintColor: COLORS.white,
  },
  iconLabel: {
    color: COLORS.purple,
    fontFamily: FONTS.families.OpenSansSemiBold,
    fontSize: scale(FONTS.sizes.xSmall),
    letterSpacing: scale(0.5),
    marginTop: scale(5),
    textTransform: 'capitalize',
  },
  iconLabelCopyCC: {
    color: COLORS.purple,
    fontFamily: FONTS.families.OpenSansSemiBold,
    fontSize: scale(FONTS.sizes.mSmall),
    letterSpacing: scale(0.5),
    marginTop: scale(5),
    textTransform: 'capitalize',
  },
  iconLabelCopy: {
    color: COLORS.purple,
    fontFamily: FONTS.families.OpenSansSemiBold,
    fontSize: scale(FONTS.sizes.small),
    letterSpacing: scale(0.5),
    marginTop: scale(5),
    textTransform: 'capitalize',
  },
  
  iconText: {
    color: COLORS.white,
    fontFamily: FONTS.families.OpenSansSemiBold,
    fontSize: scale(FONTS.sizes.slarge),
    
  },
   iconTextLabel: {
    color: COLORS.primaryDark,
    fontFamily: FONTS.families.OpenSansSemiBold,
    fontSize: scale(FONTS.sizes.xSmall),
    letterSpacing: scale(0.5),
    marginTop: scale(5),
    textTransform: 'capitalize',
  },
  headerText: {
    color: COLORS.white,
    fontFamily: FONTS.families.OpenSansSemiBold,
    fontSize: scale(FONTS.sizes.large),
    letterSpacing: scale(0.5),
    marginLeft: scale(8),
    textTransform: 'capitalize',
  },
  customCardStyle: {
    borderWidth: scale(1),
    borderColor: COLORS.borderGrey,
  },
});
