// Importing
import {StyleSheet} from 'react-native';
import {scale} from 'react-native-size-matters';
import COLORS from '../../config/COLORS';
import FONTS from '../../config/FONTS';

// Exporting
export default BUTTON_STYLES = StyleSheet.create({
  button: {
    width: '100%',
    height: scale(40),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(5),
    marginVertical: scale(5),
    backgroundColor: COLORS.primary,
    borderWidth: scale(1),
    borderColor: COLORS.primary,
  },
  buttonPositive: {
    width: '100%',
    height: scale(40),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(5),
    marginVertical: scale(5),
    backgroundColor: COLORS.primary,
    color:COLORS.white,
    borderWidth: scale(1),
    borderColor: COLORS.primary,
  },
  buttonNigative: {
    width: '100%',
    height: scale(40),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(5),
    marginVertical: scale(5),
    backgroundColor: COLORS.red,
    borderWidth: scale(1),
    color:COLORS.white,
    borderColor: COLORS.red,
  },
  buttonNigativeSmall: {
    width: scale(40),
    height: scale(40),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(5),
    marginRight:scale(10),
    marginVertical: scale(5),
    backgroundColor: COLORS.red,
    borderWidth: scale(1),
    color:COLORS.white,
    borderColor: COLORS.red,
    borderRadius:10
  },
  buttonwarningSmall: {
    width: scale(40),
    height: scale(40),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(5),
    marginRight:scale(10),
    marginVertical: scale(5),
    backgroundColor: COLORS.red,
    borderWidth: scale(1),
    color:COLORS.white,
    borderColor: COLORS.orange,
    borderRadius:10
  },
  buttonWarning: {
    width: '100%',
    height: scale(40),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(5),
    marginVertical: scale(5),
    backgroundColor: COLORS.orange,
    borderWidth: scale(1),
    borderColor: COLORS.orange,
    color:COLORS.white,
  },
  buttonSmall: {
    width: '70%',
    height: scale(10),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(5),
    marginVertical: scale(5),
    backgroundColor: COLORS.primary,
    borderWidth: scale(1),
    borderColor: COLORS.primary,
  },
  buttonxSmall: {
    width: '40%',
    height: scale(40),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(5),
    backgroundColor: COLORS.primary,
    borderWidth: scale(1),
    borderColor: COLORS.primary,
  },
  buttonLabel: {
    fontSize: scale(FONTS.sizes.medium),
    fontFamily: FONTS.families.OpenSansSemiBold,
    letterSpacing: scale(0.5),
    textTransform: 'uppercase',
    color: COLORS.white,
  },
  buttonTransperant: {
    width: '100%',
    height: scale(40),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(5),
    marginVertical: scale(5),
    backgroundColor: COLORS.white,
    borderWidth: scale(1),
    color:COLORS.black,
    borderColor: COLORS.white,
    
  },
});
